on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Every day at 2:00am
  release:
    types: [published]

name: Publish binaries to release 2

jobs:

  publish-ubuntu-18:
    name: Publish binary for ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --locked
    # No need to upload binaries for dry run (cron)
    - name: Upload binaries to release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.MEILI_BOT_GH_PAT }}
        file: target/release/meilisearch
        asset_name: meilisearch-linux-amd64-ubuntu-18
        tag: ${{ github.ref }}

  publish-ubuntu-20:
    name: Publish binary for ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --locked
    # No need to upload binaries for dry run (cron)
    - name: Upload binaries to release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.MEILI_BOT_GH_PAT }}
        file: target/release/meilisearch
        asset_name: meilisearch-linux-amd64-ubuntu-20
        tag: ${{ github.ref }}

  publish-ubuntu-18-container:
    name: Publish binary for ubuntu-18.04 (container)
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
    - uses: actions/checkout@v3
    - name: Install rustup
      run: |
        apt-get update && apt-get install -y curl
        apt-get install build-essential -y
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - name: Build
      run: cargo build --release --locked
    # No need to upload binaries for dry run (cron)
    - name: Upload binaries to release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.MEILI_BOT_GH_PAT }}
        file: target/release/meilisearch
        asset_name: meilisearch-linux-amd64-ubuntu-18-container
        tag: ${{ github.ref }}
