name: Automate some steps of release management
# No git flow handled here

on:
  milestone:
    types: [created]

jobs:
  get-release-version:
    runs-on: ubuntu-latest
    outputs:
      is-patch: ${{ steps.check-patch.outputs.is-patch }}
    env:
      MILESTONE_VERSION: ${{ github.event.milestone.title }}
    steps:
      - uses: actions/checkout@v3
      - name: Check if this release is a patch release only
        id: check-patch
        run: |
          echo version: $MILESTONE_VERSION
          if [[ $MILESTONE_VERSION =~ ^v[0-9]+\.[0-9]+\.0$ ]]; then
            echo 'This is NOT a patch release'
            echo ::set-output name=is-patch::false
          elif [[ $MILESTONE_VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo 'This is a patch release'
            echo ::set-output name=is-patch::true
          else
            echo 'Not a valid format of release, check the Milestones title.'
            echo 'Should be vX.Y.Z'
            exit 1
          fi

  create-roadmap-issue:
    needs: get-release-version
    # Create the roadmap issue if the release is not only a patch release
    if: needs.get-release-version.outputs.is-patch == 'false'
    runs-on: ubuntu-latest
    env:
      # GH_TOKEN: ${{ secrets.MEILI_BOT_GH_PAT }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_TEMPLATE: issue-template.md
      MILESTONE_VERSION: ${{ github.event.milestone.title }}
      MILESTONE_URL: ${{ github.event.milestone.html_url }}
      MILESTONE_DUE_ON: ${{ github.event.milestone.due_on }}
    steps:
      - uses: actions/checkout@v3
      - name: Download the issue template
        run: curl -s https://raw.githubusercontent.com/meilisearch/core-team/main/issue-templates/roadmap-issue.md > $ISSUE_TEMPLATE
      - name: Replace all empty occurences in the templates
        run: |
          # Replace all <<version>> occurences
          sed -i "s/<<version>>/$MILESTONE_VERSION/g" $ISSUE_TEMPLATE

          # Replace all <<milestone_id>> occurences
          milestone_id=$(echo $MILESTONE_URL | cut -d '/' -f 7)
          sed -i "s/<<milestone_id>>/$milestone_id/g" $ISSUE_TEMPLATE

          # Replace release date if exists
          if [[ ! -z $MILESTONE_DUE_ON ]]; then
            date=$(echo $MILESTONE_DUE_ON | cut -d 'T' -f 1)
            sed -i "s/Release date\: 20XX-XX-XX/Release date\: $date/g" $ISSUE_TEMPLATE
          fi
      - name: Create the issue
        run: |
          gh issue create \
            --title "$MILESTONE_VERSION ROADMAP" \
            --label 'epic,impacts docs,impacts integrations,impacts cloud' \
            --body-file $ISSUE_TEMPLATE \
            --milestone $MILESTONE_VERSION

  create-changelog-issue:
    needs: get-release-version
    # Create the changelog issue if the release is not only a patch release
    if: needs.get-release-version.outputs.is-patch == 'false'
    runs-on: ubuntu-latest
    env:
      # GH_TOKEN: ${{ secrets.MEILI_BOT_GH_PAT }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_TEMPLATE: issue-template.md
      MILESTONE_VERSION: ${{ github.event.milestone.title }}
      MILESTONE_DUE_ON: ${{ github.event.milestone.due_on }}
    steps:
      - uses: actions/checkout@v3
      - name: Download the issue template
        run: curl -s https://raw.githubusercontent.com/meilisearch/core-team/main/issue-templates/changelog-issue.md > $ISSUE_TEMPLATE
      - name: Replace all empty occurences in the templates
        run: |
          # Replace all <<version>> occurences
          sed -i "s/<<version>>/$MILESTONE_VERSION/g" $ISSUE_TEMPLATE

          # Replace release date if exists
          if [[ ! -z $MILESTONE_DUE_ON ]]; then
            date=$(echo $MILESTONE_DUE_ON | cut -d 'T' -f 1)
            sed -i "s/\(<<milestone_due_on>>\)/\($date\)/g" $ISSUE_TEMPLATE
          else
            sed -i "s/\(<<milestone_due_on>>\)//g" $ISSUE_TEMPLATE
          fi
      - name: Create the issue
        run: |
          gh issue create \
            --title "Create release changelogs for $MILESTONE_VERSION" \
            --label 'impacts docs,documentation' \
            --body-file $ISSUE_TEMPLATE \
            --milestone $MILESTONE_VERSION \
            --assignee curquiza

  create-release-label:
    needs: get-release-version
    runs-on: ubuntu-latest
    env:
      # GH_TOKEN: ${{ secrets.MEILI_BOT_GH_PAT }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MILESTONE_VERSION: ${{ github.event.milestone.title }}
    steps:
      - uses: actions/checkout@v3
      - name: Create the $MILESTONE_VERSION label
        # gh api repos/meilisearch/meilisearch/labels
        run: |
          gh api repos/curquiza/meilisearch/labels
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -f name="$MILESTONE_VERSION" \
            -f description="PRs/issues solved in $MILESTONE_VERSION" \
            -f color='ff5ba3'
# labalize-issues: when closing -> open an issue. if: github.event.actions == 'created'

