name: Automate some steps of release management
# No git flow handled here

on:
  milestone:
    types: [created]

jobs:
  get-release-version:
    runs-on: ubuntu-latest
    outputs:
      is-patch: ${{ steps.check-patch.outputs.is-patch }}
    env:
      MILESTONES_VERSION: ${{ github.event.milestone.title }}
    steps:
      - uses: actions/checkout@v3
      - name: Check if this release is a patch release only
        id: check-patch
        run: |
          echo version: $MILESTONES_VERSION
          if [[ $MILESTONES_VERSION =~ ^v[0-9]+\.[0-9]+\.0$ ]]; then
            echo 'This is NOT a patch release'
            echo ::set-output name=is-patch::false
          elif [[ $MILESTONES_VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo 'This is a patch release'
            echo ::set-output name=is-patch::true
          else
            echo 'Not a valid format of release, check the Milestones title.'
            echo 'Should be vX.Y.Z'
            exit 1
          fi

  create-roadmap-issue:
    needs: get-release-version
    # Create the roadmap issue if the release is not only a patch release
    if: needs.get-release-version.outputs.is-patch == 'false'
    runs-on: ubuntu-latest
    env:
      # GH_TOKEN: ${{ secrets.MEILI_BOT_GH_PAT }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_TEMPLATE: roadmap-issue-template.md
      MILESTONES_VERSION: ${{ github.event.milestone.title }}
      MILESTONES_URL: ${{ github.event.milestone.html_url }}
      MILESTONES_DUE_ON: ${{ github.event.milestone.due_on }}
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ needs.get-release-version.outputs.is-patch }}
      - name: Download the issue template
        run: curl -s https://raw.githubusercontent.com/meilisearch/core-team/main/issue-templates/roadmap-issue.md > $ISSUE_TEMPLATE
        # if [[ ! -z $MILESTONES_DUE_ON ]]
        #  | cut -d 'T' -f 1
        #   sed -i "s/Release date\: 20XX-XX-XX/Release date\: $MILESTONES_DUE_ON/g" $ISSUE_TEMPLATE
        # fi
          # sed -i "s/<<milestones_url>>/$MILESTONES_URL/g" $ISSUE_TEMPLATE
      - name: Replace all empty occurences in the templates
        run: |
          sed -i "s/<<version>>/$MILESTONES_VERSION/g" $ISSUE_TEMPLATE
      - name: Create the issue
        run: |
          gh issue create \
            --title 'Create release changelogs for $MILESTONES_VERSION' \
            --label 'epic,impacts docs,impacts integrations,impacts cloud' \
            --body-file $ISSUE_TEMPLATE \
            --milestone $MILESTONES_VERSION \
            --assignee curquiza

# create-roadmap-issue:
# create-label:
# labalize-issues: when closing -> open an issue
